[network]
rpcport=21842
p2pPort=21843
listen=0
rpcbind=127.0.0.1
rpcAllowRemote=0
rpcMaxConnections=16
automaticReorg=0

[default]
node.ip=127.0.0.1
node.port=21842

[chain]
chainName=TRUMain
networkType=mainnet
